### ISSUE TITLE
Shutting down via the window X (or any other signal) doesn't allow for clean exit

### ISSUE THREAD

**Issue by hippietim** [ArthurSonzogni/FTXUI#117]
When the framerwork enters the Loop, it tales over signal handlers.  This would be fine if it handled them by alerting the main process loop to exit.  Instead it calls some cleanup code and exits from the exception thread.  We've got COM initialization and objects created on the main thread that we'd like to be able to cleanup.

**Comment by ArthurSonzogni** [comment]
FTXUI insert itself as a signal handler, but does call back the previously defined signal handler at the end. So existing signal handler should continue to work without conflict with FTXUI.

I need a signal handler, in order to properly cleanup the terminal state when existing FTXUI. Goal is not to let the user with unusable terminal.

What would you like to see as API for FTXUI to help you with this?

**Comment by ArthurSonzogni** [comment]
Hey @hippietim,

I landed a few patches. Could you confirm your problem has been fixed or bring some suggestions?

**Comment by MichaelGoulding** [comment]
std::raise(0); causes an abort on Windows

**Comment by MichaelGoulding** [comment]
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: <removed by me>
File: minkernel\crts\ucrt\src\appcrt\misc\signal.cpp
Line: 456

Expression: ("Invalid signal or error", 0)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by ArthurSonzogni** [comment]
Thanks @MichaelGoulding ! This should be fixed now.

**Comment by hippietim** [comment]
The issue for us is that if we exit the process from the signal thread, we have no way of executing on the main thread again which is where we must do COM cleanup.
