### ISSUE TITLE
handle terminal resize (SIGWINCH) 

### ISSUE THREAD

**Issue by codehz** [ArthurSonzogni/FTXUI#3]
![image](https://user-images.githubusercontent.com/13158903/60394044-9326e700-9b50-11e9-87ce-d0e7d1c87f89.png)
when I resize the terminal..
but It will redraw when new character was typed

possible fix: just add a SIGWINCH signal handler that clear the content and redraw

**Comment by codehz** [comment]
I think it can be called by user..
but the another problem is the Clear method cannot clear the screen when the new size is smaller than old size.. it will leave some unwanted lines like this
![image](https://user-images.githubusercontent.com/13158903/60394148-4d6b1e00-9b52-11e9-8081-0de5265e0dfe.png)

**Comment by ArthurSonzogni** [comment]
Thanks for reporting this! Yes it was a known problem. It needs to be fixed.

**About 1**, yes we can use SIGWINCH. Alternatively, I am wondering if there is a terminal escape sequence I could send so that it will send us back any "resize event" automatically. I will have to check the documentation:
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html

**About 2**. I think we can send a terminal escape code to "disable line wrapping". Then the terminal won't break the document on resize.
I think it is:
DISABLE_LINE_WRAP = "\e[?45h"
 ENABLE_LINE_WRAP = "\e[?7h"

**Comment by codehz** [comment]
1. there is no escape sequence for resize event... (at least on linux) the only way is to handle SIGWINCH signal.
2. sounds like a good idea.

**Comment by ArthurSonzogni** [comment]
I applied **1.**. It should work now.

I tried **2.**
However it didn't improve things.
In some terminals like xterm, lines are not wrapping on window resize. 
In other like gnome-terminal, lines are wrapped, even if I try disabling it.

**Comment by codehz** [comment]
aha, it is already good enough
