### ISSUE TITLE
Windows build error using msvc 142

### ISSUE THREAD

**Issue by YuzukiTsuru** [ArthurSonzogni/FTXUI#59]
```
D:\include\ftxui/screen/color.hpp(22): error C2059: syntax error: "("
D:\include\ftxui/screen/color.hpp(22): error C2091: function return function
D:\include\ftxui/screen/color.hpp(22): error C2143: syntax error: missing "," (before "|")
D:\include\ftxui/screen/color.hpp(22): error C2535: "ftxui::Color::Color(void)": Member function has been defined or declared
D:\include\ftxui/screen/color.hpp(17): note: see the declaration of "ftxui::Color::Color"
D:\include\ftxui/screen/color.hpp(22): error C2059: syntax error: "|"
D:\include\ftxui/screen/color.hpp(22): error C2059: syntax error: ")"
D:\include\ftxui/screen/color.hpp(22): error C2238: Unexpected mark is located before ";"
```

**Comment by ArthurSonzogni** [comment]
Thanks for reporting this.
The continuous integration build it on windows and there was no problem:
https://travis-ci.com/github/ArthurSonzogni/FTXUI/jobs/406888815

Are you sure this isn't caused by your usage? Are you just compiling the FTXUI library, or are you compiling your project?

**Comment by YuzukiTsuru** [comment]
I will confirm it and build example

**Comment by robinlinden** [comment]
This is caused by a conflict with a macro defined in a Windows header: https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-rgb. I ran into the [same issue](https://github.com/robinlinden/hastur/blob/de632f61058a2efad193ee9cd7e52ced3a0e0f68/browser/main.cpp) by including an ASIO header before including FTXUI headers.

I would open a PR fixing it, but the options are
1. `#undef RGB` which could break user code if adding FTXUI includes.
2. Change the name of the static function to something like `Rgb`. Breaking change, but maybe the nicer option?

If you let me know what you think, I can open a PR with a fix. :)

**Comment by ArthurSonzogni** [comment]
Thanks @robinlinden!

I think this window header you mentioned shouldn't have defined such a macro with this very common name.
I believe option 1 might be worth it to be tried?

A windows header is breaking us, we break it in return? ;-)

**Comment by robinlinden** [comment]
Sounds good, will open a PR in a bit! :) If users really want the macro, they can always move the Windows header to after the line where ftxui's headers are included and everything will work.
