### ISSUE TITLE
Corrupted terminal when force exiting FTXUI

### ISSUE THREAD

**Issue by WinstonPrivacy** [ArthurSonzogni/FTXUI#617]
Great library, I've been using it for 6 months now. However, I've come across a persistent problem where my app hangs while exiting main() - but only when FtxUI is enabled.

Having traced this down as far as possible, I see that FtxUI keeps a Screen thread running at exit. I've tried to abort this using:

`screen.ExitLoopClosure()();`

Unfortunately, this doesn't seem to work. As it is critical that my app does not hang when shut down, I've had to resort to using sys.exit() to force close everything. This has the unfortunate side effect of corrupting the SSH client (terminal session) input so that one of two things happens, either A) no keystrokes are visible on the screen or B) any movement of the mouse cursor over the screen generates control characters.

I'm wondering if there is a way to effectively shut down FtxUI to avoid these issues?

**Comment by Eleshz** [comment]
I have this same problem actually! 

![image](https://user-images.githubusercontent.com/79333862/232053750-6a3cd918-8b7d-4259-a3a6-b62cbd94886b.png)

(The "ContinueRender" is for a | Maybe that disables the container component)

When I click the button that this is under: 
![image](https://user-images.githubusercontent.com/79333862/232054031-18db9580-977b-4083-a3b4-0b3a220a0d1a.png)

This occurs:

![image](https://user-images.githubusercontent.com/79333862/232054748-64d58ec2-d2e6-4d1c-adb2-b3e574de5abd.png)

It only happens if I move my mouse, the more I move, the more it prints. It seems to stop after about “1 1/2 consoles”.

It seems to be the same `screen.ExitLoopClosure();`
Might be me using it wrong but idk.

**Comment by Eleshz** [comment]
If you could provide a way to complete clear and delete a screen, that would be a huge help!

**Comment by Eleshz** [comment]
![576B65D3-E313-49B4-A42F-020F0B7EE8C3](https://user-images.githubusercontent.com/79333862/232176447-bcc838a1-b93c-4701-9a92-b8f33f97adfb.jpeg)

I don’t even know how to use this, or even if it works, but it’s seems to be exactly what I want… could you please provide an example of how to use this- or another way of deleting a screen completely…

I only want to be able to std::con and cout but moving the mouse just spews control characters either this is a bug or it’s a major flaw in FTXUI itself.

**Comment by ArthurSonzogni** [comment]
Hi both of you.

Could you provide an example I should execute, and the FTXUI version you used?

**Comment by Eleshz** [comment]
Now, if you remember me, I still don't know what I'm doing but I have made this so far:
[TitleBase.txt](https://github.com/ArthurSonzogni/FTXUI/files/11240914/TitleBase.txt)
 
 
 To "Use" click the button that says "Scramble now!"
 
 It SHOULD clear the screen so in the code you'll see me just spamming whatever code I think may clear the screen.
 
 I am using FTXUI 4.0.0
![image](https://user-images.githubusercontent.com/79333862/232259004-01a74abd-df51-4e3e-bb71-cc6f6c112a49.png)

**Comment by ArthurSonzogni** [comment]
Hi @Eleshz, your problem is you were using `exit` preventing FTXUI to exit cleanly.

You should use `ScreenInteractive::Exit()`
As a closure to pass as callback, there are also `ScreenInteractive::ExitLoopClosure()`.

Here is your example corrected:
[coucou.txt](https://github.com/ArthurSonzogni/FTXUI/files/11241691/coucou.txt)

---

@WinstonPrivacy , you said you weren't using `ScreenInteractrive::Exit()`, that's probably the reason. Could you provide a reason why you can't use it?

**Comment by Eleshz** [comment]
@ArthurSonzogni 

I don't want to exit the entire program, I just want to essentially delete the screens and wipe the slate clean, as if the screens never existed.

Also, your solution doesn't even include the button that's having the issues!
You seem to have just removed the button… why?

Long story short, I want to delete the SCREEN when clicking the button, not ALL OF FTXUI.

Thank you

**Comment by Eleshz** [comment]
Also if I use this combination:
![image](https://user-images.githubusercontent.com/79333862/232315376-01127abf-6aff-4762-9914-eb2879c1965f.png)

Then everything is removed, but it also removes the cursor or something so I can't type anymore.

**Comment by ArthurSonzogni** [comment]
@Eleshz Don't try to communicate with the terminal yourself. Don't exit the Screen, but display a different component.

You can for instance use: `Container::Tab(components, int displayed_component)` to switch the view in between multiples `components`.
You can take this example where:
https://github.com/ArthurSonzogni/FTXUI/blob/1397c1023434f63bf1aa5eeea2e6d6943178a745/examples/component/tab_horizontal.cpp#L42-L49

**Comment by Eleshz** [comment]
Is there any way to exit the screen anyway?
I want to go back to std::cin and std::cout, but the screen is always in the way.

**Comment by Eleshz** [comment]
I should also ask if this is a workaround:

Could you switch to a component that doesn't return anything? So you could get a completely blank cmd that can be used to used with cout and cin? As in I could type as if no screens existed in the first place?

@ArthurSonzogni

**Comment by ArthurSonzogni** [comment]
Sure, you can temporarilly uninstall/install the screen so that you can interleave use of `std::cin` / `std::cout`. You have to wrap a function with `ScreenInteractive::WithRestoredIO: fun -> fun`.

See example:
- https://github.com/ArthurSonzogni/FTXUI/blob/1397c1023434f63bf1aa5eeea2e6d6943178a745/examples/component/with_restored_io.cpp#L20-L27

**Comment by Eleshz** [comment]
Yes!!!!!

This is exactly what I wanted!!!! Thank you so much for all the help!!

I hope I didn't bother you as much as it seemed lol, I wish you good luck!
