### ISSUE TITLE
No `.gitignore` to ignore the build folder

### ISSUE THREAD

**Issue by avighnac** [ArthurSonzogni/FTXUI#669]
FTXUI uses CMake which generates a bunch of build files in the `build/` directory, maybe it's a good idea to create a `.gitignore` file to ignore this?

**Comment by ArthurSonzogni** [comment]
Hello!

I never needed. I carefully add new files using `git add <file>`, this is very rarely needed. Most often, I only need to add updated files using `git add -u`.

I don't really understand what could be the need for a .gitignore file, outside of allowing you to randomly call `git add . I consider the latter to be a bad practice, because you could add unwanted files if your `.gitignore` is not `specific` enought. It will always be not enought.

You don't want an exclude-list (`.gitignore`). What would be better/safer is an include-list, but it turns out this is already something internal to git and you can add entries to it using `git add <file>`.

Maybe you know a different reason to need a `.gitignore` file?

**Comment by avighnac** [comment]
In a collaborative environment, it's important to maintain consistency and accommodate different preferences for adding files (ot everyone may prefer manually adding files!). Including a .gitignore file can be helpful in preventing accidents where people inadvertently push binaries, IDE-specific folders like .vscode, and other unwanted files. There are no downsides to adding a .gitignore file, as the careful can continue to remain careful.

At the end of the day, it is your choice whether you wish to add one, but [it is best practice](https://opensource.com/article/20/8/dont-ignore-gitignore).

**Comment by avighnac** [comment]
@jtbraun I think you need to `git add` the files beforehand

**Comment by jtbraun** [comment]
> @jtbraun I think you need to `git add` the files beforehand

Okay, but then what's the point of all the `!`-prefixed rules, if they don't actually un-ignore those paths so that `git status` lists them? Isn't then the current `.gitignore` file equivalent to one that only contains `*`, and isn't such a `.gitignore` file kind of pointless, as it's no different than `git` just not reporting anything about files it doesn't know about?

I'm clearly missing something.

**Comment by avighnac** [comment]
@jtbraun This is normal behaviour! Even without a `.gitignore`, you need to add files using `git add <filename>` before `git` tracks them and they show up in `git status`.

**Comment by jtbraun** [comment]
*shrug* That's not how most projects I've seen make use of .gitignore. My preference would be if you create a new source file (*.cpp), `git status` would show you it as an untracked file, and `git add .` would add it, because it's not ignored.

**Comment by ArthurSonzogni** [comment]
> shrug That's not how most projects I've seen make use of .gitignore. My preference would be if you create a new source file (*.cpp), git status would show you it as an untracked file, and git add . would add it, because it's not ignored.

You are right. I would expect the file to show up in git status. We should fix this.

**Comment by ArthurSonzogni** [comment]
@jtbraun, I found the solution. It got merged into:
https://github.com/ArthurSonzogni/FTXUI/pull/688*

(Thanks for reporting this)!
