### ISSUE TITLE
Seeking experience in debugging ftxui

### ISSUE THREAD

**Issue by OutXiao** [ArthurSonzogni/FTXUI#749]
Hi @ArthurSonzogni 
I am currently completing a relatively large project based on ftxui, but as the project expands, some bugs are not easy to debug. Therefore, I would like to seek the author's debugging experience based on ftxui development. How to debug the project?
thanks

**Comment by ArthurSonzogni** [comment]
Hi @OutXiao,

That's a difficult question, because this is at the same time large and the potential answers are often hard to articulate.

The more you debug, the more you are good at it. That's the best answer I have. Observing recurrents patterns often compound over time allowing to make it easier. 

If you have some git URL to show your project, I might be able to provide some recommmandations.

**Comment by OutXiao** [comment]
I appreciate your advise! 
Thanks
BRs.
