### ISSUE TITLE
RGBA's Alpha not work in alacritty

### ISSUE THREAD

**Issue by dty2** [ArthurSonzogni/FTXUI#906]
rgba not work
my code is 
```
...
    return false;
  });
  //this->content = emain;
  this->content = Renderer([](bool focused){ return text("hello") | bgcolor(Color::RGBA(21, 101, 192, 130)); });
  std::thread t([&]{
    function->postevent = std::bind(&Tui::postevent, this, std::placeholders::_1);
    function->start();
  });
  screen->Loop(content);
...
```
when I set "a" is 130, the result is
![2024-07-25_23-24](https://github.com/user-attachments/assets/694d03c8-5045-4468-95d1-42ffe4fd62f5)
when I set "a" is 110, the result is 
![2024-07-25_23-25](https://github.com/user-attachments/assets/7fb850ae-427d-4175-a855-ac298d48a80f)
I notice that the max of alpha is 255,. the min of alpha is 0
so I get the result is when I set alpha less than 126, it is not transparent, and when I set alpha more than 127, it is thorough transparent 
I don't want it thorough, I want make it translucence.
So, Am I mistaken? Or, something was wrong...
I think it is my terminal problem, so will I try to install other terminal to try again...

**Comment by dty2** [comment]
I think I found the problem... it is my alacritty. I set alacirtty transparent, but alacirtty not transparent for text, it just transparent for background. (such as nvim, it is not transparent too...)
So, the Color::RGBA not work. I don't know the bottom the render rule and code. I think something must be changed...

**Comment by dty2** [comment]
I try some other terminal like kitty.
I set kitty transparent 0.8
and run my code. RGBA still not work...
What terminal does author use? I want to try again...

**Comment by ArthurSonzogni** [comment]
Hello,
Terminals do not support an alpha channel. The transparency we expect from FTXUI is when stacking multiple elements on top of each other using `dbox`.

**Comment by glowysourworm** [comment]
@dty2 I had the same problem trying to get transparency to work. If this is what he was talking about, he didn't explain that it would work. Just compose two components. Since he has a signature like: ftxui::Color::RGBA, you'd expect that there's a reason to have an alpha channel, even if the terminal somehow doesn't support it.

This worked in my code:

_component = ftxui::Container::Vertical({
	ftxui::Container::Vertical({

		// Your components

	}) | ftxui::bgcolor(ftxui::Color::RGBA(0, 0, 255, 20))
}) | ftxui::bgcolor(ftxui::Color::RGB(0, 0, 0));

The dim blue output is the semi-transparent background

<img width="741" height="291" alt="Image" src="https://github.com/user-attachments/assets/690adc15-aa0f-4395-b120-db8866fff0e3" />
