### ISSUE TITLE
Dynamically update menu items

### ISSUE THREAD

**Issue by kiddersmxj** [ArthurSonzogni/FTXUI#928]
Hi,
I'm not sure if this is a bug or something that I am not supposed to be doing but I have attached a semi minimum reproducible code for this bug I have found.

I am trying to dynamically update a menu container which I do with a function called `rebuild_ui()` however after calling this method it breaks the relationship between the input box and the menu - both can be 'focused' or at least highlighted at the same time and the TakeFocus() function does not work properly anymore. Please see the attached code to see for yourself.

Press e to input, type and then enter, the menu becomes selected again and a new entry is added. Then press e again and both menu and input box seem to be highlighted, then when you enter text and press enter the focus does not switch back to the menu. What is going on here? Is this a bug or is there a much easier way to do something like this?

https://codeshare.io/9bQA31

Thanks.

**Comment by ArthurSonzogni** [comment]
It looks like the `main_container` still contains the previous `tab_selection`.
On the other side the `main_renderer` is renderering the new one.


I am sorry updating `ftxui::Component` isn't as easy/functional as updating `ftxui::Element`. That's a design flow that is now difficult to remove.

In your case I wouldn't execute:
```
tab_selection = ...
```
because this would create a new instance.

I would do:
```cpp
tab_selection->DetachAllChildren();
for (size_t i = 0; i < tab_entries.size(); ++i) {
    tab_selection->Add(MenuEntry(tab_entries[i]) | ftxui::size(ftxui::WIDTH, ftxui::EQUAL, 25));
}
```

**Comment by kiddersmxj** [comment]
WOW! That works. Thank you so much you have no idea how frustrating that was.
