### ISSUE TITLE
Only use UTF-8 chars

### ISSUE THREAD

**Issue by PoloNX** [ArthurSonzogni/FTXUI#943]
I'm porting ftxui on nintendo switch but the terminal is very basic and doesn't support unicode chars. Is there a way to only use UTF-8 ?
![2024112813175800](https://github.com/user-attachments/assets/acebcd83-fc12-4866-8f33-5fc3577b45b9)

**Comment by ArthurSonzogni** [comment]
Hello!

> `ftxui on nintendo switch`

Lol. I wouldn't have imagined someone would do it. :rofl: 
Does the switch offers a terminal?

>  Is there a way to only use UTF-8 ?

![image](https://github.com/user-attachments/assets/71d055de-f3b0-4bd6-ae8c-41aff770e15f)

Always as been.

For instance, you can see I had to use a specific option for MSVC compiler, because it is only the default on clang/gcc:
https://github.com/ArthurSonzogni/FTXUI/blob/55af678fb9f535d958f278b70c8d9773ad996021/cmake/ftxui_set_options.cmake#L46-L50

Maybe the compiler you are using does need some specific option?


Or, maybe you mean using ascii symbols instead of unicode? In this case, nothing builtin at the moment. I only have the [`FTXUI_MICROSOFT_TERMINAL_FALLBACK`](https://github.com/ArthurSonzogni/FTXUI/blob/edaa7a24e7bc58605fa08a35360ea7fb581752eb/CMakeLists.txt#L19) for Microsoft terminal to remove unsupported characters and "mitigate" bugs in Microsoft terminals.

---

Maybe you can shre additional information about your setup?
